/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas.Vista;


import Seguridad.Controlador.clsBitacora;
import Ventas.Controlador.clsCotizacion;
import Seguridad.Controlador.clsUsuarioConectado;
import Ventas.Controlador.clsPedidos;
import Ventas.Controlador.clsFacturas;
import Ventas.Controlador.clsTienda;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author visitante
 */
public class frmConsultaDevolucion extends javax.swing.JInternalFrame {

    public void llenadoDeCombos() {
        /*EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        List<Empleado> empleados = empleadoDAO.select();
        cbox_empleado.addItem("Seleccione una opción");
        for (int i = 0; i < empleados.size(); i++) {
            cbox_empleado.addItem(empleados.get(i).getNombreEmpleado());
        } */
    }


    private DefaultTableModel modeloTabla;
    
    public frmConsultaDevolucion() {
        initComponents();
        llenadoDeTablasCotizaciones();
        llenadoDeCombos();
    }

    int codigoAplicacion = 3008;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2DevCons = new javax.swing.JLabel();
        lbusuDevCons = new javax.swing.JLabel();
        jScrollPane1DevCons = new javax.swing.JScrollPane();
        jTable1DevCons = new javax.swing.JTable();
        jScrollPaneDevReg = new javax.swing.JScrollPane();
        tblDevConsulta = new javax.swing.JTable();
        lbDevReg = new javax.swing.JLabel();
        btnVerDetalleDev = new javax.swing.JButton();
        lbInsDevReg = new javax.swing.JLabel();
        btnAyudaConDev = new javax.swing.JButton();

        lb2DevCons.setForeground(new java.awt.Color(204, 204, 204));
        lb2DevCons.setText(".");

        jTable1DevCons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1DevCons.setViewportView(jTable1DevCons);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Devoluciones");
        setVisible(true);

        tblDevConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneDevReg.setViewportView(tblDevConsulta);

        lbDevReg.setText("Ventas Devueltas:");

        btnVerDetalleDev.setText("Ver Detalle");
        btnVerDetalleDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalleDevActionPerformed(evt);
            }
        });

        lbInsDevReg.setText("Haz clic en la factura que quieras trabajar, luego presiona un botón:");

        btnAyudaConDev.setText("Ayuda");
        btnAyudaConDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaConDevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(lbDevReg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbInsDevReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDevReg, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAyudaConDev)
                        .addGap(131, 131, 131))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerDetalleDev)
                        .addGap(123, 123, 123))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDevReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lbInsDevReg)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDevReg, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnVerDetalleDev)
                        .addGap(148, 148, 148)
                        .addComponent(btnAyudaConDev)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDetalleDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleDevActionPerformed
        // TODO add your handling code here:
        
// Crea una instancia de FrmConsultaCotizacionDetalle
                int filaSeleccionada = tblDevConsulta.getSelectedRow();
                int cotidSeleccionado = Integer.valueOf(tblDevConsulta.getValueAt(filaSeleccionada, 0).toString());
                frmConsultaDevolucionDetalle frmConsulta = new frmConsultaDevolucionDetalle(cotidSeleccionado);

                // Agrega el FrmConsultaCotizacionDetalle al JDesktopPane
                JDesktopPane desktopPane = getDesktopPane();
                desktopPane.add(frmConsulta);
                frmConsulta.setVisible(true);
                frmConsulta.toFront();
                int resultadoBitacora=0;
                    clsBitacora bitacoraRegistro = new clsBitacora();
                    resultadoBitacora = bitacoraRegistro.setIngresarBitacora(clsUsuarioConectado.getIdUsuario(),codigoAplicacion,"QRY"); 

    }//GEN-LAST:event_btnVerDetalleDevActionPerformed

    private void btnAyudaConDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaConDevActionPerformed
        // TODO add your handling code here:
        //Carlos Javier Sandoval Catalán
        //9959-21-1324
        try {
            if ((new File("src\\main\\java\\ventas\\ayuda\\ayudaconfac.chm")).exists()) {
                Process p = Runtime
                .getRuntime()
                .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ventas\\ayuda\\ayudaconfac.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no fue encontrada");
            }
            //System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAyudaConDevActionPerformed

     public void llenadoDeTablasCotizaciones() {
        DefaultTableModel modelo = new DefaultTableModel(){
            public boolean isCellEditable(int row, int column) {
                return false; // Desactivar la edición de las celdas
            }
        };
        modelo.addColumn("Id Factura");
        modelo.addColumn("Id Pedido");
        modelo.addColumn("Id Cliente");
        modelo.addColumn("Id Vendedor");
        modelo.addColumn("Id Tienda");
        modelo.addColumn("Fecha");
        modelo.addColumn("Total");
        clsFacturas cotizacion = new clsFacturas();
        //VendedorDAO vendedorDAO = new VendedorDAO();
        List<clsFacturas> listaCotizaciones = cotizacion.getListadoDevoluciones();
        tblDevConsulta.setModel(modelo);
        String[] dato = new String[7];
        for (int i = 0; i < listaCotizaciones.size(); i++) {
            dato[0] = Integer.toString(listaCotizaciones.get(i).getIdFactura());
            dato[1] = Integer.toString(listaCotizaciones.get(i).getIdPedido());
            dato[2] = Integer.toString(listaCotizaciones.get(i).getIdCliente());
            dato[3] = Integer.toString(listaCotizaciones.get(i).getIdVendedor());
            dato[4] = Integer.toString(listaCotizaciones.get(i).getIdTienda());
            dato[5] = listaCotizaciones.get(i).getFechaFactura();
            dato[6] = Double.toString(listaCotizaciones.get(i).getTotalFactura());
            modelo.addRow(dato);
        }              

                    

}
    
public int obtenerCotidSeleccionado() {
    int filaSeleccionada = tblDevConsulta.getSelectedRow();
    int cotidSeleccionado = (int) tblDevConsulta.getValueAt(filaSeleccionada, 0);
    return cotidSeleccionado;
}

public int obtenerClienteidSeleccionado() {
    int filaSeleccionada = tblDevConsulta.getSelectedRow();
    int cotidSeleccionado = (int) tblDevConsulta.getValueAt(filaSeleccionada, 2);
    return cotidSeleccionado;
}


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyudaConDev;
    private javax.swing.JButton btnVerDetalleDev;
    private javax.swing.JScrollPane jScrollPane1DevCons;
    private javax.swing.JScrollPane jScrollPaneDevReg;
    private javax.swing.JTable jTable1DevCons;
    private javax.swing.JLabel lb2DevCons;
    private javax.swing.JLabel lbDevReg;
    private javax.swing.JLabel lbInsDevReg;
    private javax.swing.JLabel lbusuDevCons;
    private javax.swing.JTable tblDevConsulta;
    // End of variables declaration//GEN-END:variables


}