/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas.Vista;


import Seguridad.Controlador.clsBitacora;
import Ventas.Controlador.clsCotizacion;
import Seguridad.Controlador.clsUsuarioConectado;
import Ventas.Controlador.clsPedidos;
import Ventas.Controlador.clsFacturas;
import Ventas.Controlador.clsTienda;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author visitante
 */
public class frmConsultaFacturaDetalle extends javax.swing.JInternalFrame {

    public void llenadoDeCombos() {
        /*EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        List<Empleado> empleados = empleadoDAO.select();
        cbox_empleado.addItem("Seleccione una opción");
        for (int i = 0; i < empleados.size(); i++) {
            cbox_empleado.addItem(empleados.get(i).getNombreEmpleado());
        } */
    }


    private DefaultTableModel modeloTabla;
    
    public frmConsultaFacturaDetalle(int cotidSeleccionado) {
        initComponents();
        llenadoDeTablasPedidos(cotidSeleccionado);
        llenadoDeCombos();
    }

    int codigoAplicacion = 3007;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2FacConsDet = new javax.swing.JLabel();
        lbusuFacConsDet = new javax.swing.JLabel();
        jScrollPane1FacDet = new javax.swing.JScrollPane();
        jTable1FacDet = new javax.swing.JTable();
        jScrollPaneFacRegDet = new javax.swing.JScrollPane();
        tblPedFacCons = new javax.swing.JTable();
        lbFacDet = new javax.swing.JLabel();

        lb2FacConsDet.setForeground(new java.awt.Color(204, 204, 204));
        lb2FacConsDet.setText(".");

        jTable1FacDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1FacDet.setViewportView(jTable1FacDet);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Facturas");
        setVisible(true);

        tblPedFacCons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneFacRegDet.setViewportView(tblPedFacCons);

        lbFacDet.setText("Detalle de la Factura:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPaneFacRegDet, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(lbFacDet)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lbFacDet)
                .addGap(33, 33, 33)
                .addComponent(jScrollPaneFacRegDet, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void llenadoDeTablasPedidos(int cotidSeleccionado) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id Factura");
        modelo.addColumn("Codigo Producto");
        modelo.addColumn("Precio Producto");
        modelo.addColumn("Cantidad Producto");
        modelo.addColumn("Descuento");
        modelo.addColumn("Impuestos");
        modelo.addColumn("Sub Total");
        clsFacturas cotizacion = new clsFacturas();
        List<clsFacturas> listaCotizaciones = cotizacion.getListadoCotizacionesDetalle(cotidSeleccionado);
        tblPedFacCons.setModel(modelo);
        String[] dato = new String[7];
        for (int i = 0; i < listaCotizaciones.size(); i++) {
            dato[0] = Integer.toString(listaCotizaciones.get(i).getIdFactura());
            dato[1] = Integer.toString(listaCotizaciones.get(i).getCodigoProducto());
            dato[2] = Double.toString(listaCotizaciones.get(i).getPrecioProducto());
            dato[3] = Double.toString(listaCotizaciones.get(i).getCantidadProducto());
            dato[4] = Double.toString(listaCotizaciones.get(i).getDescuentoFactura());
            dato[5] = Double.toString(listaCotizaciones.get(i).getImpuestosFactura());
            dato[6] = Double.toString(listaCotizaciones.get(i).getTotalIndividualFactura());
            
            modelo.addRow(dato);
        }              

                    

}
    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1FacDet;
    private javax.swing.JScrollPane jScrollPaneFacRegDet;
    private javax.swing.JTable jTable1FacDet;
    private javax.swing.JLabel lb2FacConsDet;
    private javax.swing.JLabel lbFacDet;
    private javax.swing.JLabel lbusuFacConsDet;
    private javax.swing.JTable tblPedFacCons;
    // End of variables declaration//GEN-END:variables


}